version: '3'

services:

  image-server:
    image: gat-image-server:latest
    ports: 
      - "9090:9090"
    volumes:
      - /var/www/tiling-images/trees:/var/www/images
    restart: unless-stopped

  mongo:
    image: mongo

  redis:
    image: redis

  grow-a-tree:
    container_name: grow-a-tree
    image: grow-a-tree:latest
    ports:
      - "8089:8080"
    restart: unless-stopped
